#ifndef __ControlParam_Interface__
#define __ControlParam_Interface__

/**
@file
Subclass of ControlParam, which is generated by wxFormBuilder.
*/

#include "Layout.h"

//// end generated include

/** Implementing ControlParam */
class ControlParam_Interface : public ControlParam
{
	public:
		/** Constructor */
		ControlParam_Interface( wxWindow* parent );
	//// end generated class members

};

#endif // __ControlParam_Interface__
