#ifndef __Dialog_Interface__
#define __Dialog_Interface__

/**
@file
Subclass of ControlDialog, which is generated by wxFormBuilder.
*/

#include "Layout.h"

//// end generated include

/** Implementing ControlDialog */
class Dialog_Interface : public ControlDialog
{
	protected:
		// Handlers for ControlDialog events.
		void OnExit( wxCloseEvent& event );
	public:
		/** Constructor */
		Dialog_Interface( wxWindow* parent );
	//// end generated class members


};

#endif // __Dialog_Interface__
