#ifndef __HelpDialog_Interface__
#define __HelpDialog_Interface__

/**
@file
Subclass of HelpDialog, which is generated by wxFormBuilder.
*/

#include "Layout.h"

//// end generated include

/** Implementing HelpDialog */
class HelpDialog_Interface : public HelpDialog
{
	public:
		/** Constructor */
		HelpDialog_Interface( wxWindow* parent );
	//// end generated class members

};

#endif // __HelpDialog_Interface__
