#ifndef __MainFrame_Interface__
#define __MainFrame_Interface__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "Layout.h"

//// end generated include

#pragma once
#include "Dialog_Interface.h"
#include "Config.h"
#include <wx/msgdlg.h>
#include <wx/dcbuffer.h>
#include "Draw.h"
#include "Primitives.h"
#include "ControlParam_Interface.h"
#include "HelpDialog_Interface.h"
#include <wx/filedlg.h>
#include <wx/dirdlg.h>

/** Implementing MainFrame */
class MainFrame_Interface : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void OnExit( wxCloseEvent& event );
		void MainFrameOnLeftDown( wxMouseEvent& event );
		void MainFrameOnLeftUp( wxMouseEvent& event );
		void MainFrameOnMotion( wxMouseEvent& event );
		void Refresh( wxUpdateUIEvent& event );
		void m_ControlPanelSelection( wxCommandEvent& event );
		void m_FunctionConfigSelection( wxCommandEvent& event );
		void m_SaveAsSelection( wxCommandEvent& event );
		void m_QuitSelection( wxCommandEvent& event );
		void m_AboutSelection( wxCommandEvent& event );
		void m_HelpSelection( wxCommandEvent& event );
		void DrawCanvasOnChar( wxKeyEvent& event );
		void DrawCanvasOnLeftDown( wxMouseEvent& event );
		void DrawCanvasOnLeftUp( wxMouseEvent& event );
		void DrawCanvasOnMotion( wxMouseEvent& event );
		void DrawCanvasOnMouseWheel( wxMouseEvent& event );
		void DrawCanvasOnRightDown( wxMouseEvent& event );
		void DrawCanvasOnRightUp( wxMouseEvent& event );
	public:
		/** Constructor */
		MainFrame_Interface( wxWindow* parent );
	//// end generated class members

		Dialog_Interface* controldialog;
		HelpDialog_Interface* helpdialog;
		ControlParam_Interface* controlparam;
		Config* current_config;
		std::vector<Segment> data;
		std::vector<Segment> arrow;
		
		wxBitmap _pic;
		wxImage MyImage;
};

#endif // __MainFrame_Interface__
